version: "3"

services:
  app:
    build: .
    image: roomcounter
    restart: unless-stopped
    volumes:
      - ./app/roomcounter:/app/roomcounter
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.roomcounter.rule=Host(`roomcounter.${DOMAIN}`)"
      - "traefik.http.routers.roomcounter.tls.certresolver=le"
      - "traefik.http.routers.roomcounter.entrypoints=websecure"
    environment:
      - APP_NAME=Room Counter
      - INITIAL_USER=admin
      - INITIAL_PASSWORD=roomcounter2000
      - INITIAL_ROOM_NAME=Draussen
      - DB_URI=postgresql://postgres:roomcounter2000@postgres:5432/postgres
    networks:
      - default
      - traefik

  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=roomcounter2000
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

networks:
  traefik:
    external: true
